### PR TITLE
Add support for SOF2 for 2p runs.

### PR DESCRIPTION
**Pull request by totto82**
Make it possible to use SOF2 in combination with either
SGFN og SWFN for gas-oil and water-oil case respectively.

Need OPM/opm-parser#1157 for the tests to pass.

### CODE REVIEW

**Comment by andlaus** [comment]
Looks good, merge at will

**Comment by andlaus** [comment]
jenkins build this opm-parser=1157 please

**Comment by andlaus** [comment]
okay, OPM/opm-parser#1157 has been merged, so this can go in too. Thanks for the patch!

**Comment by andlaus** [comment]
for some reason travis does not seem to like this. (in this case not because of the usual timeout but because the compareECLFiles_flow+SPE5CASE1 opm-simulators test fails: https://travis-ci.org/OPM/opm-material/builds/306670470?utm_source=email&utm_medium=notification)

**Comment by totto82** [comment]
Master was broken for SPE5CASE1 for while. Should be fixed now.

**Comment by andlaus** [comment]
ok, cool

**Pull request merged**
