### PR TITLE
Remove Unused.hpp

### PR DESCRIPTION
**Pull request by akva2**
Replace with standard [[maybe_unused]] annotations and/or anonymous variables.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this opm-models=701 please

**Review by blattms — APPROVED** [review]
Looks good. you just missed some stuff in opm-models it seems.

**Comment by akva2** [comment]
jenkins build this opm-models=701 opm-simulators=3986 please

**Pull request merged**
