### PR TITLE
remove unused variable

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Hmmmm - master red?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
Uhm, it seems to be fine now? You only see the warning in downstream, ie, opm-simulators.å

**Comment by joakim-hove** [comment]
> Uhm, it seems to be fine now?

Sure - thanks; merging.

**Pull request merged**
