### PR TITLE
some cleanups in ConstantCompressibilityBrinePvt

### PR DESCRIPTION
**Pull request by akva2**
- Get rid of unused types
- Expose the used typedef
- Reorder members to match init list in constructor

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-models=589 opm-simulators=2318 please

**Comment by akva2** [comment]
@totto82 this and downstreams should be mergeable now, independent of the other things we discussed regarding the brine implementation / test.

**Comment by akva2** [comment]
ping @totto82

**Comment by totto82** [comment]
Thanks for the cleanups.

**Pull request merged**
