### PR TITLE
[for testing] Revert "Improving dynamic evaluation"

### PR DESCRIPTION
**Pull request by GitPaean**
Reverts OPM/opm-material#327

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=1760 please

**Comment by andlaus** [comment]
what's the motivation for this PR?

**Comment by GitPaean** [comment]
> what's the motivation for this PR?

It was used to test the impact of the original DynamicEvaluation and new DyanmicEvaluation. 

However, it turns out that some code of need to be changed a little bit in opm-simulators before the testing. 

I will come back to this.

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=1771 please

**Comment by andlaus** [comment]
> However, it turns out that some code of need to be changed a little bit in opm-simulators before the testing.

since jenkins is currently happy, I propose that we go for the fixup PRs which you need directly instead of reverting and doing everything from scratch. This should reduce the delta, but IMO how to proceed is ultimately your choice/responsibility...

**Comment by GitPaean** [comment]
> since jenkins is currently happy with master, I propose that we go for the fixup PRs directly instead of reverting this and redoing everything from scratch. This should reduce code churn, but IMO how to proceed is ultimately your choice/responsibility...

Yes. I am just collecting more information for now.  As stated, this PR is only for testing, not intended to be merged at all for now.

**Comment by andlaus** [comment]
> This PR is only for testing, not intended to be merged at all for now.

ah, okay. I did not really catch the latter...

**Comment by GitPaean** [comment]
https://ci.opm-project.org/job/opm-material-PR-builder/146/ produced the same results with https://ci.opm-project.org/job/opm-simulators-PR-builder/1395/ . 

We do not need to revert this. We can just discuss whether we want https://github.com/OPM/opm-simulators/pull/1760 .

**Comment by GitPaean** [comment]
for testing

**Comment by GitPaean** [comment]
is `for testing` also used to trigger jenkins build test?

**Comment by GitPaean** [comment]
or the action of re-opening triggered it?

**Pull request closed without merging**
