### PR TITLE
Add missing opm-parser headers

### PR DESCRIPTION
**Pull request by jokva**
opm-parser pull #695
https://github.com/OPM/opm-parser/pull/695

Can be merged before upstream.

### CODE REVIEW

**Comment by andlaus** [comment]
that patch looks very innocent even without OPM/opm-parser#695 so I merge it right now.

did you check that the ebos simulator (from the ewoms) still compiles?

**Comment by jokva** [comment]
I'll have an extra look, but if it's disabled by default then it hasn't been checked.

**Comment by andlaus** [comment]
> I'll have an extra look, but if it's disabled by default then it hasn't been checked.

it is enabled (and compiled by default) as soon as a working dune-cornerpoint is detected. you need to include eWoms in your build though...

**Comment by jokva** [comment]
It works for me™

**Comment by andlaus** [comment]
> It works for me™

cool! thanks for testing.

**Pull request merged**
