### PR TITLE
Change static intialization of CO2 tables to avoid function call, use construction.

### PR DESCRIPTION
**Pull request by atgeirr**
This has been verified to work (unlike the current master) with clang on my system. I believe this is good to be merged when green.

Thanks to Arne Morten for the patch!

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by blattms** [comment]
Would be nice to know what the acually fix was. Is the move from `static` to `static const`/static constexpr` for the members of CO2Tables and the static initialization of them via inline or the move from arrays to vectors,

**Comment by akva2** [comment]
As atgeirr wrote, the fix is moving from a function for initialization, to initialization through construction. The move to vector is mostly to work around annoying const double array not castable to const double**. As a bonus it makes the added constructor more versatile.

**Review by totto82 — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
