### PR TITLE
changed fluid to put water equations first

### PR DESCRIPTION
**Pull request by hnil**
Move water to first equation. This make implementation of cpr simpler.

### CODE REVIEW

**Comment by andlaus** [comment]
making the phase indices different from the component indices was a conscious decision to catch incorrect usage. (i.e., using a phase index where a component index is required or vice versa). sounds like your CPR code currently has some issues in this respect?

**Comment by GitPaean** [comment]
> making the phase indices different from the component indices was a conscious decision to catch incorrect usage.

Should we change component indices? then we will get rid of a lot indices conversion functions in `opm-simulators` .

**Comment by andlaus** [comment]
> Should we change component indices? 

no. You should fix the user code. (if necessary, create a phaseToCompIdx[phaseIdx] array.)

**Comment by GitPaean** [comment]
>  (if necessary, create a phaseToCompIdx[phaseIdx] array.)

That is the thing we want to avoid.

**Comment by andlaus** [comment]
> Creating an array is basically the same with a conversion function.

yes, you can also create a conversion function if you prefer. phases are something very different from components, so using the same indices to access both should be considered a felony IMO.

**Comment by GitPaean** [comment]
> yes, you can also create a conversion function if you prefer. phases are something very different from components, so using the same indices to access both should be considered a felony IMO.

Maybe, but the fact is the component indices are not same either.

**Comment by atgeirr** [comment]
Since keeping the indices different may be a good idea to provoke errors if abused, I am testing now with changed phase indices as well. (Basically swapping oil and water for phases too.) If that works all should be happy...

**Comment by andlaus** [comment]
> Maybe, but the fact is the component indices are not same either.

what do you mean with this? my point is that you should not be able to use a component index to specify a phase without doing some translation before...

@atgeirr: since the eWoms and ebos code should not mix the phase and component indices it should work fine. I'm not sure about `flow`'s well model, though.

**Comment by GitPaean** [comment]
> what do you mean with this?

like the function `ebosCompIdxToFlowCompIdx()`. I am not familiar with ebos enough to comment to dare to change these functions.  We got rid of quite some already, but there are still some that makes people nerves.

**Comment by atgeirr** [comment]
> @atgeirr: since the eWoms and ebos code should not mix the phase and component indices it should work fine. I'm not sure about `flow`'s well model, though.

It compiles fine, but I get plenty of regression errors. Maybe there are some abuses in the output code? Not sure, needs checking unfortunately.

**Comment by GitPaean** [comment]
> what do you mean with this? my point is that you should not be able to use a component index to specify a phase without doing some translation before...

I now see the discussion went to the wrong direction due to me. I will shut up now. Sorry for the noise.

**Comment by andlaus** [comment]
> Maybe there are some abuses in the output code? 

that's very possible. (Sorry, I forgot that part in my previous comment.)

**Comment by andlaus** [comment]
this PR might have a point: to catch such index mixups in the current code, maybe the component indices should be changed after all. They should not be the same as the phase indices with the same name, though. Maybe to something like 0 for gas, 1 for water and 2 for oil?

**Comment by andlaus** [comment]
to be clear: While I won't allow the appearance of generality for user code that essentially hard-codes the indices, I'm not objecting, to changing the default order of the indices if these indices lead to better *performance*. Any arbitrary ordering must lead to *correct* results, though. (since the latter does not seem to be the case at the moment, there's a bug somewhere. I'll probably add a test using a fluid system that uses completely different indices to opm-simulators soon in order to prevent such regressions from happening.)

**Comment by atgeirr** [comment]
> since the latter does not seem to be the case at the moment

Note that this applies to the phase indices, not component indices.

**Comment by andlaus** [comment]
> Note that this applies to the phase indices, not component indices.

reordering the component indices is currently required for correctness with @hnil's current version of CPR, not just for performance?

**Comment by atgeirr** [comment]
I have now looked into the question of why changing phase indices failed, and it is was simply because I did not realize I also had to change the `phaseToSolventCompIdx_` and `phaseToSoluteCompIdx_` arrays. The fluid system test in opm-material ensures this, so no need to add anything. With this, it seems everything (except the equil test, which has hardcoded indices that must be fixed -- PR coming) works with changed indices, which is a good sign!

Knowing that changing phase indices (so they are different from component indices) should work fine, I'll run tests for this PR.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by andlaus** [comment]
this is superseeded by #326.

**Pull request closed without merging**
