### PR TITLE
changed: consistently use std::array

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-models=706 opm-simulators=4005 please

**Comment by akva2** [comment]
benchmark please opm-models=706 opm-simulators=4005

**Comment by akva2** [comment]
iik. it's still being benchmarked.

**Comment by blattms** [comment]
:flushed: Well, then it some things are even slower than me. Well I don't expect much change, and we can always revert....

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                                                                   | Relative |
| ------- | ----------------------------------------------------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1                                                      | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8                                                      | 1.009    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1                                                      | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGASMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWATMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8                                                      | 0.989    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGASMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWATMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1                                               | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FOPT (Total Oil Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FGPT (Total Gas Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWPT (Total Water Production At End Of Run) | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FOIT (Total Oil Injection At End Of Run)    | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWIT (Total Water Injection At End Of Run)  | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FGASMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWATMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8                                               | 0.988    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FOPT (Total Oil Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FGPT (Total Gas Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWPT (Total Water Production At End Of Run) | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FOIT (Total Oil Injection At End Of Run)    | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWIT (Total Water Injection At End Of Run)  | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FGASMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWATMBE                                     | 1        |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1748

**Pull request merged**
