### PR TITLE
Add tests using Scalar=float (try 2).

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR revised all tests such that Scalar=double and Scalar=float is tested. All tests compile, some of the test do not work with float and are therefore disabled for now.

### CODE REVIEW

**Comment by andlaus** [comment]
ok, looks good. once you have merged my fixes into your branch, I'll merge the result into master.

**Comment by joakim-hove** [comment]
Now - this PR looks fine to me; however I wonder whether the templated scalar is necessary at all? I guess it will mostly be `double`- and the unfamiliar `Scalar` where I was expecting a `double` certainly adds to the cognitive load of reading the code. Is it worth it?

**Comment by andlaus** [comment]
> however I wonder whether the templated scalar is necessary at all? 

it is beneficial IMO and it also is not much effort, so the price/benefit ratio is pretty good, I think.

> I guess it will mostly be double- and the unfamiliar Scalar where I was expecting a double certainly adds to the cognitive load of reading the code. Is it worth it?

in eWoms most simulations for the flash model use quadruple precision floating point types (if the compiler supports them) to get better convergence. Besides that, using single-precision floating point scalars potentially leads to better performance than double precision ones, so I guess it is worth the additional mental load. (Also note that the localized automatic differentiation code heavily depends on the ability of using Scalar != double.)

**Comment by dr-robertk** [comment]
@joakim-hove: some time ago somebody claimed that using single precision would speed up the simulator. I don't think it will, but right now it's not even possible to switch to anything other then double because it's hard coded all over the place. In opm-material we still have the chance to prevent this. This is basically the patch for that.

**Pull request merged**
