### PR TITLE
Using getInputGrid API from Parser

### PR DESCRIPTION
**Pull request by pgdr**
Using new EclipseState.getInputGrid API in Parser

See OPM/opm-parser#769

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this opm-parser=769 please

**Comment by andlaus** [comment]
seems fine, if jenkins is happy, merge it at your convenience

**Comment by joakim-hove** [comment]
Travis - do your thing

**Comment by joakim-hove** [comment]
Hmmm - I might have started the merging to early; seems this one is not green. I will merge now - and patch immediately if needed. Sorry.

**Comment by pgdr** [comment]
It's a 7 character diff with no semantic change (only name change in API).  I would be surprised if a patch is needed.

**Pull request merged**
