### PR TITLE
EclMultiplexerMaterialParams: use shared_ptr instead of void*.

### PR DESCRIPTION
**Pull request by dr-robertk**
This seems to fix a problem that occurs when this class is copied. However, I advise for careful investigation of whether to use pointers here.

### CODE REVIEW

**Comment by andlaus** [comment]
have you tested this for performance on Norne? if there are no regressions, feel free to press green.

**Comment by dr-robertk** [comment]
No, and I also don't think this should be merged. This is simply a fix for making some of @totto82 latest experiments work. I'll let you know when this is done. Btw, void* ....

**Comment by dr-robertk** [comment]
I have now tested this change with Norne and I don't see any change in performance.

**Comment by dr-robertk** [comment]
jenkins build this with downstreams please

**Comment by dr-robertk** [comment]
jenkins build this with downstreams please

**Comment by dr-robertk** [comment]
This should also go in once the tests succeeded since it fixes a memory problem with the EclMultiplexerMaterialParams class.

**Comment by andlaus** [comment]
the tests succeeded. since there does not seem to be a performance penaltiy, it goes in now. thanks.

**Pull request merged**
