### PR TITLE
fixed: do not use Opm:: prefix when inside namespace Opm

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
There are a few more of these, e.g., in [`EclStone2Material.hpp`](https://github.com/OPM/opm-material/blob/90e66eabb05c7f0c8b4e8093930bac6d67e56118/opm/material/fluidmatrixinteractions/EclStone2Material.hpp#L357).  Do you want/need to address those too?

**Comment by akva2** [comment]
need, no, they did not confuse the compiler, but i kinda want to yes.

**Comment by bska** [comment]
> i kinda want to yes.

Okay.  Do we hold off on merging this until you've addressed those or is the current PR sufficient to do what you want?

**Comment by akva2** [comment]
i am already working on it but as I have work in queue waiting on this, it would be great if this can be merged first.

**Comment by bska** [comment]
> i am already working on it but as I have work in queue waiting on this, it would be great if this can be merged first.

Very good.  I'll merge this now.

**Pull request merged**
