### PR TITLE
Co2brinepvt ref pr

### PR DESCRIPTION
**Pull request by totto82**
Some improvements to the co2brinepvt script

Should be merged after #498 since it adapts the scripts accordingly.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
test failures in [SPE1CASE1_BRINE](https://ci.opm-project.org/job/opm-material-PR-builder/196/testReport/junit/(root)/mpi/compareParallelSim_flow_SPE1CASE1_BRINE/)

**Comment by totto82** [comment]
Strange, the failure is in the parallel run. ... I will try Jenkins again.

**Comment by totto82** [comment]
jenkins build this please

**Comment by blattms** [comment]
Cool, seems to work now.

**Comment by akva2** [comment]
hrm. it likely means something is unstable?

**Comment by blattms** [comment]
Can I see the output for passed tests on jenkins? [compareParallelSim_flow_SPE1CASE1_BRINE](https://ci.opm-project.org/job/opm-material-PR-builder/197/testReport/(root)/mpi/compareParallelSim_flow_SPE1CASE1_BRINE/) is not very verbose.

**Comment by akva2** [comment]
It only keeps verbose output for failed tests, https://ci.opm-project.org/job/opm-material-PR-builder/196/testReport/junit/(root)/mpi/compareParallelSim_flow_SPE1CASE1_BRINE/

**Comment by blattms** [comment]
might have found the cause see [PR  684 in opm-models](https://github.com/OPM/opm-models/pull/684/files#r854000348). Well it is just an educated guess that in parallel different values might be used on the processes.

**Pull request merged**
