### PR TITLE
fix the index into salinity in the BrineCo2Pvt model

### PR DESCRIPTION
**Pull request by totto82**
Thanks to valgrind

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
This is a trivial bugfix. I will self-merge tomorrow if nobody objects.

**Comment by atgeirr** [comment]
> This is a trivial bugfix. I will self-merge tomorrow if nobody objects.

No need...

**Comment by bska** [comment]
> This is a trivial bugfix. I will self-merge tomorrow if nobody objects.

I'll merge it right away myself.

**Pull request merged**
