### PR TITLE
changed: avoid long vectors of shared ptrs

### PR DESCRIPTION
**Pull request by akva2**
this use a lot of memory with many elements.

For a case I'm looking at this brought memory usage down from
58.9GB (61GB peak) to 47.3GB (which is also the peak).

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by alfbr** [comment]
benchmark please

**Comment by blattms** [comment]
I guess the numbers are for a serial run or are we doing the computatioj on the unloadbalanced grid?

**Comment by akva2** [comment]
it's all serial.

**Comment by akva2** [comment]
Added some more commits that brings it down to 46.5949GB. Another big gain can be had by disabling the non-conditional diffusion storage in the intensive quantities, but that is separate.

**Comment by akva2** [comment]
jenkins build this please

**Comment by alfbr** [comment]
These are very impressive gains! Needless to say, we really look forward to seeing these improvements in master :-)

**Comment by atgeirr** [comment]
Read through, looks good, merging!

**Pull request merged**
