### PR TITLE
Remove saturated branches

### PR DESCRIPTION
**Pull request by hnil**
This fix the tables in ecl way and add test for saturated values
- add a fluid object which only evaluate in the table

### CODE REVIEW

**Comment by andlaus** [comment]
before I look more deeply into this: is this a successor of #313? also, the PR would profit quite a bit if the patches were re-organized into logically connected parts...

**Comment by hnil** [comment]
This is a successor of #313

**Comment by hnil** [comment]
Sorry for not being very structured in the patches. But if this is good we chould rearrange it.

**Comment by andlaus** [comment]
rearranging would be good. if this is basically only a single functionality change, squashing them together would suffice.

**Comment by hnil** [comment]
[1D_THREEPHASE_high.pdf](https://gi
[1D_THREEPHASE_low.pdf](https://github.com/OPM/opm-material/files/2575357/1D_THREEPHASE_low.pdf)
thub.com/OPM/opm-material/files/2575356/1D_THREEPHASE_high.pdf)

It seems like for more sensitive cases this change really matters.

**Comment by GitPaean** [comment]
Cool, this basically closes the issue https://github.com/OPM/opm-simulators/issues/235 .

**Comment by andlaus** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by andlaus** [comment]
this has not been visited for a long time. is it worthwhile to put the effort in testing this as thoroughly as it needs to be? if yes, please make jenkins happy first.

**Comment by totto82** [comment]
I started testing this before Christmas but was interrupted. I can test it again. As I see this PR it contains two things; the interpolation/extrapolation of tables and the simplified blackoil fluid system. I will focus my testing on the first part. As I understands it (I have not looked at all the details, and may be wrong) the simplified blackoil fluid system is mostly for convenience and should not change anything.

**Comment by andlaus** [comment]
Ok, the BlackOilFluid{State,System} stuff should then be ripped out of this PR?!

**Comment by GitPaean** [comment]
> Ok, the BlackOilFluid{State,System} stuff should then be ripped out of this PR?!

Maybe a separate PR for ease of testing and reviewing. 

The interpolation/extrapolation part is highly desirable since it solves a long-living issue.

**Comment by totto82** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
> the FPR issue reported in #

Here something is missing, what did you mean?

**Comment by totto82** [comment]
> Here something is missing, what did you mean?

Yes. the issue is:  OPM/opm-simulators#1663

**Comment by atgeirr** [comment]
Followup PR in #328, closing.

**Pull request closed without merging**
